#Set map type
map_type: costmap

#Set the tolerance we're willing to have for tf transforms
transform_tolerance: 1

#Obstacle marking parameters
obstacle_range: 1.5
max_obstacle_height: 2.0
raytrace_range: 1.5

#The footprint of the robot 
footprint: [[-0.25, -0.25], [-0.25, 0.25], [0.35, 0.25], [0.35, -0.25]]

#Inscribed and circumscribed radius 
inscribed_radius: 0.2
circumscribed_radius: 0.3

#Cost function parameters
inflation_radius: 0.2
cost_scaling_factor: 5.0

#The cost at which a cell is considered an obstacle when a map is read from the map_server
lethal_cost_threshold: 100

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
