global_costmap: 

  #Set the global and robot frames for the costmap
  global_frame: odom
  robot_base_frame: base_footprint

  #Set the update and publish frequency of the costmap
  update_frequency: 1.0

  resolution: 0.05

  static_map: false
  rolling_window: true

  outline_map: false
